[package]
name = "espcam"
version = "0.1.0"
authors = ["Kezi <keziolio123@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"
lto = true

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "embassy", "esp-idf-svc/native"]

pio = ["esp-idf-svc/pio"]
std = ["alloc", "esp-idf-svc/binstart", "esp-idf-svc/std"]
alloc = ["esp-idf-svc/alloc"]
nightly = ["esp-idf-svc/nightly"]
experimental = ["esp-idf-svc/experimental"]
embassy = ["esp-idf-svc/embassy-sync", "esp-idf-svc/critical-section", "esp-idf-svc/embassy-time-driver"]

[dependencies]
log = { version = "0.4", default-features = false }
embedded-svc = "0.26"
anyhow = "1.0.79"

bstr = { version = "1.8.0", default-features = false }
tokio = { version = "*", features = ["rt", "time", "sync","macros"] }
lazy_static = "1.4.0"
uuid = { version = "1.2.2", default-features = false, features = ["macro-diagnostics"] }
rgb565 = "0.1.3"
image = { version = "0.25", default-features = false, features = ["png"] }
frankenstein = { version = "0.30", default-features = false, features = ["telegram-trait"]}
serde = { version = "1", features = ["derive"]}
serde_json = { version = "1"}

idotmatrix = {git = "https://github.com/Kezii/idotmatrix.git"}

# esp dependencies
# bluetooth : https://github.com/taks/esp32-nimble
esp32-nimble = "0.8.1"
esp-idf-hal = "0.44"
# peripheral like wifi
esp-idf-svc = { version = "0.49" , default-features = false }
# this give Failed to run Python dependency check.  Python:
    # Error: 255
esp-idf-sys = "0.35"
thiserror = "1.0.56"

toml-cfg = "=0.1.3"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = "components/esp32-camera"
bindings_header = "components/bindings.h"
bindings_module = "camera"


[build-dependencies]
#  https://github.com/esp-rs/embuild
# A library with many utilities for building embedded frameworks, libraries, and other artifacts in a cargo build script.
embuild = "0.32"
toml-cfg = "=0.1.3"